export type GameProgressInfo = {
    timeLeft: number;
    word: string;
};

export type GameState =
    | 'waiting'
    | 'changing_turn'
    | 'playing'
    | 'end_turn'
    | 'ending'
    | 'end';

export type PayloadEvent = {
    action: string;
    start: {
        X: number;
        Y: number;
    };
    end: {
        X: number;
        Y: number;
    };
    color: string;
};

export const wordsList: string[] = [
    'civic education',
    'art',
    'physical education',
    'craft',
    'geometry',
    'algebra',
    'friend',
    'classmate',
    'teacher',
    'pal',
    'close friend',
    'best friend',
    'old friend',
    'lesson',
    'exercise',
    'test',
    'homework',
    'break',
    'kindergarten',
    'primary school',
    'secondary school',
    'high school',
    'university',
    'private school',
    'college',
    'library',
    'computer room',
    'laboratory',
    'backpack',
    'book',
    'pencil',
    'pen',
    'crayon',
    'ruler',
    'scissors',
    'chair',
    'desk',
    'eraser',
    'rubber',
    'clip',
    'glue',
    'pencil case',
    'paper',
    'marker',
    'compass',
    'globe',
    'dictionary',
    'notebook',
    'sharpener',
    'doctor',
    'driver',
    'baker',
    'chef',
    'engineer',
    'fire fighter',
    'dentist',
    'accountant',
    'architect',
    'businessman',
    'bank clerk',
    'diplomat',
    'cashier',
    'greengrocer',
    'pilot',
    'police',
    'interpreter',
    'worker',
    'painter',
    'farmer',
    'company',
    'factory',
    'office',
    'organization',
    'staff canteen',
    'meeting',
    'section',
    'construction site',
    'hospital',
    'farm',
    'bus',
    'taxi',
    'subway',
    'railway train',
    'coach',
    'underground',
    'car',
    'bicycle',
    'bike',
    'motorbike',
    'scooter',
    'truck',
    'lorry',
    'van',
    'tram',
    'moped',
    'boat',
    'ferry',
    'ship',
    'sailboat',
    'cargo ship',
    'cruise ship',
    'airplane',
    'plane',
    'helicopter',
    'glider',
    'hot-air balloon',
    'jet',
    'bend',
    'two-way traffic',
    'roundabout',
    'slow down',
    'slippery road',
    'no entry',
    'no horn',
    'no overtaking',
    'no parking',
    'speed limit',
    'avenue',
    'art gallery',
    'alley',
    'bank',
    'barbershop',
    'beauty salon',
    'block of flats',
    'bookstore',
    'bus stop',
    'bridge',
    'beach',
    'butchers',
    'bakery',
    'cathedral',
    'church',
    'cafe',
    'cinema',
    'clinic',
    'dress shop',
    'gift shop',
    'hospital',
    'hotel',
    'park',
    'post office',
    'pharmacy',
    'playground',
    'restaurant',
    'sidewalk',
    'swimming pool',
    'stadium',
    'stationery store',
    'square',
    'supermarket',
    'toy shop',
    'zoo',
    'blouse',
    'jacket',
    'jeans',
    'overcoat',
    'pants',
    'pullover',
    'shirt',
    'sweater',
    'skirt',
    'trousers',
    'dress',
    'cardigan',
    'pyjama',
    'suit',
    'blazer',
    'raincoat',
    't-shirt',
    'bracelet',
    'earrings',
    'glasses',
    'handbag',
    'tie',
    'necklace',
    'sunglasses',
    'watch',
    'wallet',
    'gloves',
    'boots',
    'clog',
    'loafer',
    'sandals',
    'slip-on',
    'sneaker',
    'transfer',
    'customs',
    'map',
    'price',
    'budget',
    'self catering',
    'self drive',
    'campsite',
    'avocado',
    'blueberry',
    'papaya',
    'kiwi',
    'plum',
    'peach',
    'pear',
    'air',
    'bag',
    'basket',
    'bed',
    'blanket',
    'bread',
    'brush',
    'button',
    'candle',
    'card',
    'cheese',
    'chocolate',
    'clock',
    'cloud',
    'coat',
    'coin',
    'computer',
    'cookie',
    'cup',
    'door',
    'dress',
    'dust',
    'egg',
    'envelope',
    'family',
    'father',
    'flower',
    'floor',
    'fork',
    'garden',
    'girl',
    'glasses',
    'hair',
    'hand',
    'handbag',
    'hat',
    'head',
    'house',
    'ice',
    'juice',
    'key',
    'kitchen',
    'knife',
    'lamp',
    'leaf',
    'letter',
    'light',
    'man',
    'milk',
    'mirror',
    'money',
    'morning',
    'mother',
    'mountain',
    'nail',
    'night',
    'nose',
    'oil',
    'orange',
    'park',
    'phone',
    'pillow',
    'plate',
    'pocket',
    'rain',
    'ring',
    'river',
    'road',
    'roof',
    'room',
    'salt',
    'school',
    'sea',
    'season',
    'shoe',
    'shirt',
    'shop',
    'sister',
    'sky',
    'snow',
    'soap',
    'sock',
    'spoon',
    'star',
    'stone',
    'street',
    'sugar',
    'sun',
    'table',
    'tea',
    'toothbrush',
    'towel',
    'train',
    'tree',
    'umbrella',
    'wall',
    'water',
    'window',
    'wind',
    'wood',
    'woman',
    'world',
    'apple',
    'banana',
    'cake',
    'cherry',
    'fruit',
    'glove',
    'goat',
    'hairbrush',
    'hill',
    'ice cream',
    'ladder',
    'lemon',
    'line',
    'mango',
    'monkey',
    'paint',
    'picture',
    'pineapple',
    'playground',
    'potato',
    'pumpkin',
    'rabbit',
    'rock',
    'salad',
    'sandwich',
    'shadow',
    'sheep',
    'shelf',
    'skirt',
    'sofa',
    'sound',
    'spider',
    'story',
    'strawberry',
    'swing',
    'tablecloth',
    'television',
    'tomato',
    'vegetable',
    'village',
    'watch',
    'whale',
    'winter',
    'worm',
    'yard',
    'yogurt',
    'zoo',
    'baby',
    'ball',
    'balloon',
    'bird',
    'bottle',
    'box',
    'cat',
    'child',
    'cow',
    'dog',
    'duck',
    'eye',
    'fish',
    'frog',
    'grass',
    'horse',
    'leg',
    'mouse',
    'ant',
    'apartment',
    'beach',
    'beef',
    'bee',
    'bicycle',
    'bridge',
    'butter',
    'carrot',
    'castle',
    'chicken',
    'city',
    'coffee',
    'crab',
    'desert',
    'eggplant',
    'elephant',
    'fire',
    'forest',
    'garlic',
    'gate',
    'giraffe',
    'gold',
    'honey',
    'island',
    'jeans',
    'jellyfish',
    'lake',
    'lion',
    'mask',
    'meat',
    'moon',
    'mushroom',
    'onion',
    'owl',
    'parrot',
    'pasta',
    'pigeon',
    'pizza',
    'robot',
    'rose',
    'snake',
    'thunder',
    'tiger',
    'truck',
    'volcano',
    'wallet',
    'wine',
    'wolf',
    'zebra',
];
